from dataclasses import dataclass

from board_games.ticket2ride.city import (
    City,
    ATLANTA,
    BOSTON,
    CALGARY,
    CHARLESTON,
    CHICAGO,
    DALLAS,
    DENVER,
    DULUTH,
    EL_PASO,
    HELENA,
    HOUSTON,
    KANSAS_CITY,
    LAS_VEGAS,
    LITTLE_ROCK,
    LOS_ANGELES,
    MIAMI,
    MONTREAL,
    NASHVILLE,
    NEW_ORLEANS,
    NEW_YORK,
    OKLAHOMA_CITY,
    OMAHA,
    PHOENIX,
    PITTSBURGH,
    PORTLAND,
    RALEIGH,
    SAINT_LOUIS,
    SALT_LAKE_CITY,
    SAN_FRANCISCO,
    SANTA_FE,
    SAULT_ST_MARIE,
    SEATTLE,
    TORONTO,
    VANCOUVER,
    WASHINGTON,
    WINNIPEG,
)
from board_games.ticket2ride.color import (
    Color,
    ANY,
    BLACK,
    BLUE,
    GREEN,
    ORANGE,
    PINK,
    RED,
    WHITE,
    YELLOW,
)


ROUTE_LENGTHS_TO_VALUES: dict[int, int] = {
    1: 1,
    2: 2,
    3: 4,
    4: 7,
    5: 10,
    6: 15,
}


@dataclass(frozen=True, order=True)
class Route:
    id: int
    source_city: City
    destination_city: City
    color: Color
    length: int

    @property
    def value(self) -> int:
        if self.length not in ROUTE_LENGTHS_TO_VALUES:
            raise ValueError("Invalid route length")

        return ROUTE_LENGTHS_TO_VALUES[self.length]

    def __repr__(self) -> str:
        return (
            f"{self.source_city.name} - {self.destination_city.name} ({self.color}, {self.length})"
        )


ROUTES: list[Route] = [
    Route(id=0, source_city=VANCOUVER, destination_city=CALGARY, color=ANY, length=3),
    Route(id=1, source_city=VANCOUVER, destination_city=SEATTLE, color=ANY, length=1),
    Route(id=2, source_city=VANCOUVER, destination_city=SEATTLE, color=ANY, length=1),
    Route(id=3, source_city=CALGARY, destination_city=WINNIPEG, color=WHITE, length=6),
    Route(id=4, source_city=CALGARY, destination_city=HELENA, color=ANY, length=4),
    Route(id=5, source_city=WINNIPEG, destination_city=SAULT_ST_MARIE, color=ANY, length=6),
    Route(id=6, source_city=WINNIPEG, destination_city=DULUTH, color=BLACK, length=4),
    Route(id=7, source_city=WINNIPEG, destination_city=HELENA, color=BLUE, length=4),
    Route(id=8, source_city=SAULT_ST_MARIE, destination_city=MONTREAL, color=BLACK, length=5),
    Route(id=9, source_city=SAULT_ST_MARIE, destination_city=TORONTO, color=ANY, length=2),
    Route(id=10, source_city=SAULT_ST_MARIE, destination_city=DULUTH, color=ANY, length=3),
    Route(id=11, source_city=MONTREAL, destination_city=TORONTO, color=ANY, length=3),
    Route(id=12, source_city=MONTREAL, destination_city=BOSTON, color=ANY, length=2),
    Route(id=13, source_city=MONTREAL, destination_city=BOSTON, color=ANY, length=2),
    Route(id=14, source_city=MONTREAL, destination_city=NEW_YORK, color=BLUE, length=3),
    Route(id=15, source_city=SEATTLE, destination_city=PORTLAND, color=ANY, length=1),
    Route(id=16, source_city=SEATTLE, destination_city=PORTLAND, color=ANY, length=1),
    Route(id=17, source_city=SEATTLE, destination_city=HELENA, color=YELLOW, length=6),
    Route(id=18, source_city=TORONTO, destination_city=PITTSBURGH, color=ANY, length=2),
    Route(id=19, source_city=TORONTO, destination_city=DULUTH, color=PINK, length=6),
    Route(id=20, source_city=TORONTO, destination_city=CHICAGO, color=WHITE, length=4),
    Route(id=21, source_city=BOSTON, destination_city=NEW_YORK, color=YELLOW, length=2),
    Route(id=22, source_city=BOSTON, destination_city=NEW_YORK, color=RED, length=2),
    Route(id=23, source_city=PORTLAND, destination_city=SAN_FRANCISCO, color=GREEN, length=5),
    Route(id=24, source_city=PORTLAND, destination_city=SAN_FRANCISCO, color=PINK, length=5),
    Route(id=25, source_city=SAN_FRANCISCO, destination_city=SALT_LAKE_CITY, color=ORANGE, length=5),
    Route(id=26, source_city=SAN_FRANCISCO, destination_city=SALT_LAKE_CITY, color=WHITE, length=5),
    Route(id=27, source_city=PORTLAND, destination_city=SALT_LAKE_CITY, color=BLUE, length=6),
    Route(id=28, source_city=HELENA, destination_city=DULUTH, color=ORANGE, length=6),
    Route(id=29, source_city=HELENA, destination_city=OMAHA, color=RED, length=5),
    Route(id=30, source_city=HELENA, destination_city=DENVER, color=GREEN, length=4),
    Route(id=31, source_city=HELENA, destination_city=SALT_LAKE_CITY, color=PINK, length=3),
    Route(id=32, source_city=DULUTH, destination_city=OMAHA, color=ANY, length=2),
    Route(id=33, source_city=DULUTH, destination_city=OMAHA, color=ANY, length=2),
    Route(id=34, source_city=DULUTH, destination_city=CHICAGO, color=RED, length=3),
    Route(id=35, source_city=NEW_YORK, destination_city=PITTSBURGH, color=WHITE, length=2),
    Route(id=36, source_city=NEW_YORK, destination_city=PITTSBURGH, color=GREEN, length=2),
    Route(id=37, source_city=NEW_YORK, destination_city=WASHINGTON, color=ORANGE, length=2),
    Route(id=38, source_city=NEW_YORK, destination_city=WASHINGTON, color=BLACK, length=2),
    Route(id=39, source_city=CHICAGO, destination_city=PITTSBURGH, color=ORANGE, length=3),
    Route(id=40, source_city=CHICAGO, destination_city=PITTSBURGH, color=BLACK, length=3),
    Route(id=41, source_city=CHICAGO, destination_city=SAINT_LOUIS, color=GREEN, length=2),
    Route(id=42, source_city=CHICAGO, destination_city=SAINT_LOUIS, color=WHITE, length=2),
    Route(id=43, source_city=CHICAGO, destination_city=OMAHA, color=BLUE, length=4),
    Route(id=44, source_city=PITTSBURGH, destination_city=SAINT_LOUIS, color=GREEN, length=5),
    Route(id=45, source_city=PITTSBURGH, destination_city=NASHVILLE, color=YELLOW, length=4),
    Route(id=46, source_city=PITTSBURGH, destination_city=RALEIGH, color=ANY, length=2),
    Route(id=47, source_city=OMAHA, destination_city=KANSAS_CITY, color=ANY, length=1),
    Route(id=48, source_city=OMAHA, destination_city=KANSAS_CITY, color=ANY, length=1),
    Route(id=49, source_city=OMAHA, destination_city=DENVER, color=PINK, length=4),
    Route(id=50, source_city=WASHINGTON, destination_city=PITTSBURGH, color=ANY, length=2),
    Route(id=51, source_city=WASHINGTON, destination_city=RALEIGH, color=ANY, length=2),
    Route(id=52, source_city=DENVER, destination_city=KANSAS_CITY, color=BLACK, length=4),
    Route(id=53, source_city=DENVER, destination_city=KANSAS_CITY, color=ORANGE, length=4),
    Route(id=54, source_city=DENVER, destination_city=OKLAHOMA_CITY, color=RED, length=4),
    Route(id=55, source_city=DENVER, destination_city=PHOENIX, color=WHITE, length=5),
    Route(id=56, source_city=DENVER, destination_city=SANTA_FE, color=ANY, length=2),
    Route(id=57, source_city=SANTA_FE, destination_city=OKLAHOMA_CITY, color=BLUE, length=3),
    Route(id=58, source_city=SANTA_FE, destination_city=PHOENIX, color=ANY, length=3),
    Route(id=59, source_city=KANSAS_CITY, destination_city=OKLAHOMA_CITY, color=ANY, length=2),
    Route(id=60, source_city=KANSAS_CITY, destination_city=OKLAHOMA_CITY, color=ANY, length=2),
    Route(id=61, source_city=KANSAS_CITY, destination_city=SAINT_LOUIS, color=BLUE, length=2),
    Route(id=62, source_city=KANSAS_CITY, destination_city=SAINT_LOUIS, color=PINK, length=2),
    Route(id=63, source_city=SAINT_LOUIS, destination_city=LITTLE_ROCK, color=ANY, length=2),
    Route(id=64, source_city=SAINT_LOUIS, destination_city=NASHVILLE, color=ANY, length=2),
    Route(id=65, source_city=NASHVILLE, destination_city=RALEIGH, color=BLACK, length=3),
    Route(id=66, source_city=NASHVILLE, destination_city=ATLANTA, color=ANY, length=1),
    Route(id=67, source_city=RALEIGH, destination_city=ATLANTA, color=ANY, length=2),
    Route(id=68, source_city=RALEIGH, destination_city=CHARLESTON, color=ANY, length=2),
    Route(id=69, source_city=SAN_FRANCISCO, destination_city=LOS_ANGELES, color=YELLOW, length=3),
    Route(id=70, source_city=SAN_FRANCISCO, destination_city=LOS_ANGELES, color=PINK, length=3),
    Route(id=71, source_city=LAS_VEGAS, destination_city=LOS_ANGELES, color=ANY, length=2),
    Route(id=72, source_city=SANTA_FE, destination_city=EL_PASO, color=ANY, length=2),
    Route(id=73, source_city=OKLAHOMA_CITY, destination_city=EL_PASO, color=YELLOW, length=5),
    Route(id=74, source_city=OKLAHOMA_CITY, destination_city=DALLAS, color=ANY, length=2),
    Route(id=75, source_city=OKLAHOMA_CITY, destination_city=DALLAS, color=ANY, length=2),
    Route(id=76, source_city=OKLAHOMA_CITY, destination_city=LITTLE_ROCK, color=ANY, length=2),
    Route(id=77, source_city=LITTLE_ROCK, destination_city=DALLAS, color=ANY, length=2),
    Route(id=78, source_city=LITTLE_ROCK, destination_city=NASHVILLE, color=WHITE, length=3),
    Route(id=79, source_city=LITTLE_ROCK, destination_city=NEW_ORLEANS, color=GREEN, length=3),
    Route(id=80, source_city=ATLANTA, destination_city=CHARLESTON, color=ANY, length=2),
    Route(id=81, source_city=ATLANTA, destination_city=NEW_ORLEANS, color=YELLOW, length=4),
    Route(id=82, source_city=ATLANTA, destination_city=NEW_ORLEANS, color=ORANGE, length=4),
    Route(id=83, source_city=ATLANTA, destination_city=MIAMI, color=BLUE, length=5),
    Route(id=84, source_city=CHARLESTON, destination_city=MIAMI, color=PINK, length=4),
    Route(id=85, source_city=LOS_ANGELES, destination_city=PHOENIX, color=ANY, length=3),
    Route(id=86, source_city=LOS_ANGELES, destination_city=EL_PASO, color=BLACK, length=6),
    Route(id=87, source_city=PHOENIX, destination_city=EL_PASO, color=ANY, length=3),
    Route(id=88, source_city=EL_PASO, destination_city=DALLAS, color=RED, length=4),
    Route(id=89, source_city=EL_PASO, destination_city=HOUSTON, color=GREEN, length=6),
    Route(id=90, source_city=DALLAS, destination_city=HOUSTON, color=ANY, length=1),
    Route(id=91, source_city=DALLAS, destination_city=HOUSTON, color=ANY, length=1),
    Route(id=92, source_city=HOUSTON, destination_city=NEW_ORLEANS, color=ANY, length=2),
    Route(id=93, source_city=NEW_ORLEANS, destination_city=MIAMI, color=RED, length=6),
    Route(id=94, source_city=CALGARY, destination_city=SEATTLE, color=ANY, length=4),
    Route(id=95, source_city=WASHINGTON, destination_city=RALEIGH, color=ANY, length=2),
    Route(id=96, source_city=SALT_LAKE_CITY, destination_city=DENVER, color=RED, length=3),
    Route(id=97, source_city=SALT_LAKE_CITY, destination_city=DENVER, color=YELLOW, length=3),
    Route(id=98, source_city=SALT_LAKE_CITY, destination_city=LAS_VEGAS, color=ORANGE, length=3),
    Route(id=99, source_city=RALEIGH, destination_city=ATLANTA, color=ANY, length=2),
]
