NUM_COLOR_CARDS = 12
NUM_ANY_CARDS = 14
NUM_VISIBLE_CARDS = 5
NUM_INITIAL_PLAYER_CARDS = 4
NUM_INITIAL_TRAIN_CARS = 45
NUM_LAST_TURN_CARS = 2
MAX_VISIBLE_ANY_CARDS = 2
LONGEST_PATH_POINTS = 10
MIN_PLAYERS = 2
MAX_PLAYERS = 5



